name: main

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t .
          sudo sh install.sh

      - name: Run main
        run: |
          python main.py -u ${{ secrets.EPIC_EMAIL }} -p ${{ secrets.EPIC_PASSWORD }} --once
